/**
 * generated by Xtext 2.32.0
 */
package gol.gol;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gol.gol.Grid#getAlive <em>Alive</em>}</li>
 * </ul>
 *
 * @see gol.gol.GolPackage#getGrid()
 * @model
 * @generated
 */
public interface Grid extends EObject
{
  /**
   * Returns the value of the '<em><b>Alive</b></em>' containment reference list.
   * The list contents are of type {@link gol.gol.Coordinate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alive</em>' containment reference list.
   * @see gol.gol.GolPackage#getGrid_Alive()
   * @model containment="true"
   * @generated
   */
  EList<Coordinate> getAlive();

} // Grid
