/**
 * generated by Xtext 2.32.0
 */
package gol.gol;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gol.gol.Condition#getSign <em>Sign</em>}</li>
 *   <li>{@link gol.gol.Condition#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see gol.gol.GolPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Sign</b></em>' attribute.
   * The literals are from the enumeration {@link gol.gol.ConditionSign}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign</em>' attribute.
   * @see gol.gol.ConditionSign
   * @see #setSign(ConditionSign)
   * @see gol.gol.GolPackage#getCondition_Sign()
   * @model
   * @generated
   */
  ConditionSign getSign();

  /**
   * Sets the value of the '{@link gol.gol.Condition#getSign <em>Sign</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign</em>' attribute.
   * @see gol.gol.ConditionSign
   * @see #getSign()
   * @generated
   */
  void setSign(ConditionSign value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see gol.gol.GolPackage#getCondition_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link gol.gol.Condition#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // Condition
