/*
 * generated by Xtext 2.32.0
 */
package gol.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGolScopeProvider extends DelegatingScopeProvider {
}
