/*
 * generated by Xtext 2.32.0
 */
package gol.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GolUiModule extends AbstractGolUiModule {

	public GolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
