/*
 * generated by Xtext 2.32.0
 */
package gol.ui.tests;

import com.google.inject.Injector;
import gol.ui.internal.GolActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GolUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GolActivator.getInstance().getInjector("gol.Gol");
	}

}
