/*
 * generated by Xtext 2.32.0
 */
package gol.ui;

import com.google.inject.Injector;
import gol.ui.internal.GolActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GolExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GolActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GolActivator activator = GolActivator.getInstance();
		return activator != null ? activator.getInjector(GolActivator.GOL_GOL) : null;
	}

}
