/**
 * generated by Xtext 2.32.0
 */
package gol.gol;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Of Life</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gol.gol.GameOfLife#getInitialGrid <em>Initial Grid</em>}</li>
 *   <li>{@link gol.gol.GameOfLife#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see gol.gol.GolPackage#getGameOfLife()
 * @model
 * @generated
 */
public interface GameOfLife extends EObject
{
  /**
   * Returns the value of the '<em><b>Initial Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Grid</em>' containment reference.
   * @see #setInitialGrid(Grid)
   * @see gol.gol.GolPackage#getGameOfLife_InitialGrid()
   * @model containment="true"
   * @generated
   */
  Grid getInitialGrid();

  /**
   * Sets the value of the '{@link gol.gol.GameOfLife#getInitialGrid <em>Initial Grid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Grid</em>' containment reference.
   * @see #getInitialGrid()
   * @generated
   */
  void setInitialGrid(Grid value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference.
   * @see #setRules(Rules)
   * @see gol.gol.GolPackage#getGameOfLife_Rules()
   * @model containment="true"
   * @generated
   */
  Rules getRules();

  /**
   * Sets the value of the '{@link gol.gol.GameOfLife#getRules <em>Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rules</em>' containment reference.
   * @see #getRules()
   * @generated
   */
  void setRules(Rules value);

} // GameOfLife
