/*
 * generated by Xtext 2.32.0
 */
package gol.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gol.GolRuntimeModule;
import gol.GolStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GolIdeSetup extends GolStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GolRuntimeModule(), new GolIdeModule()));
	}
	
}
