/**
 * generated by Xtext 2.32.0
 */
package gol.gol;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gol.gol.Rules#getRule <em>Rule</em>}</li>
 * </ul>
 *
 * @see gol.gol.GolPackage#getRules()
 * @model
 * @generated
 */
public interface Rules extends EObject
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' containment reference list.
   * The list contents are of type {@link gol.gol.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' containment reference list.
   * @see gol.gol.GolPackage#getRules_Rule()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRule();

} // Rules
